# Config file for CelebA dataset (200k)

output_dir: '/content/cs236_gan/data/out/dog'
structure: 'linear'
device_id: ('3')
dataset:
  img_dir: '/content/cs236_gan/data/Images'
  folder: True
  resolution: 64
sched:
  epochs: [40,80,80,80,80]
