# Config file for CelebA dataset (200k)

output_dir: '/content/cs236_gan/data/out/dog'
structure: 'linear'
device_id: ('1')
checkpoint_factor: 32
dataset:
  img_dir: '/content/cs236_gan/data/Images'
  folder: True
  resolution: 64
sched:
  epochs: [32,64,64,64,64]
